#!/bin/bash
set -e

PGADMIN_BACKUP_DIR=${PGADMIN_BACKUP_DIR:-$HOME/.backup/pgadmin}
PGADMIN_BACKUP_LOG_DIR=${PGADMIN_BACKUP_LOG_DIR:-$HOME/.backup/log}
mkdir -p $PGADMIN_BACKUP_DIR
mkdir -p $PGADMIN_BACKUP_LOG_DIR

BACKUP_DATE=$(date +%Y-%m-%d)

PGADMIN_BACKUP_FILE=pgadmin-$BACKUP_DATE.tar.gz
PGADMIN_BACKUP_LOG_FILE=pgadmin-$BACKUP_DATE.log

PGADMIN_DATA_DIR=${PGADMIN_DATA_DIR:-/var/lib/pgadmin}

tar -zvcf $PGADMIN_BACKUP_DIR/$PGADMIN_BACKUP_FILE $PGADMIN_DATA_DIR >> $PGADMIN_BACKUP_LOG_DIR/$PGADMIN_BACKUP_LOG_FILE 2>&1

find $PGADMIN_BACKUP_DIR -mindepth 1 -mtime +2 -delete
find $PGADMIN_BACKUP_LOG_DIR -mindepth 1 -mtime +2 -delete
