name: grafana

volumes:
  data:

services:
  grafana:
    image: grafana/grafana:9.2.4-ubuntu
    volumes:
      - data:/opt/bitnami
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: always
    network_mode: host
