global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
- alert.rules
- /opt/bitnami/prometheus/conf/rules/*.rules

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - host.docker.internal:9090

- job_name: node-exporter
  static_configs:
  - targets:
    - host.docker.internal:9100

- job_name: tcp-port-monitor
  metrics_path: /probe
  params:
    module:
      - tcp_connect
  static_configs:
    - targets:
      - host.docker.internal:22
      labels:
        name: ssh-port
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: host.docker.internal:9115