#! /bin/bash
read -p "Enter the date YYYYMMDDHHMM: " input_date
read -p "Enter the file name(/path/to/file): " file
echo "$input_date"
touch -t $input_date $file 
# touch -d "$(date -R -r report.csv) - 2 months 2 days" report.csv

ls -l